# Avoid methods longer than 30 lines of code
MethodLength:
  Max: 30

RedundantReturn:
  Enabled: false

Documentation:
  Enabled: false

AvoidPerlBackrefs:
  Enabled: false

LineLength:
  Max: 120

TrivialAccessors:
  Enabled: false
